# Describes the format for available Irrigation Unlimited services

enable:
  name: Enable
  description: Enable the controller or zone.
  fields:
    entity_id:
      description: Name of the Irrigation Unlimited entity.
      example: "binary_sensor.irrigation_unlimited_c1_z1"
      required: true
      selector:
        entity:
          integration: irrigation_unlimited
          domain: binary_sensor

    sequence_id:
      description: Id of the sequence to enable (entity_id should be the controller).
      example: 1
      required: false
      selector:
        number:
          min: 1
          max: 9999
          mode: box

    zones:
      description: Id(s) of the zone
      example: 1
      required: false
      selector:
        number:
          min: 0
          max: 9999
          mode: box

disable:
  name: Disable
  description: Disable the controller or zone
  fields:
    entity_id:
      description: Name of the Irrigation Unlimited entity.
      example: "binary_sensor.irrigation_unlimited_c1_z1"
      required: true
      selector:
        entity:
          integration: irrigation_unlimited
          domain: binary_sensor

    sequence_id:
      description: Id of the sequence to disable (entity_id should be the controller).
      example: 1
      required: false
      selector:
        number:
          min: 1
          max: 9999
          mode: box

    zones:
      description: Id(s) of the zone
      example: 1
      required: false
      selector:
        number:
          min: 0
          max: 9999
          mode: box

toggle:
  name: Toggle
  description: Toggle the enable/disable status of controller or zone.
  fields:
    entity_id:
      description: Name of the Irrigation Unlimited entity.
      example: "binary_sensor.irrigation_unlimited_c1_z1"
      required: true
      selector:
        entity:
          integration: irrigation_unlimited
          domain: binary_sensor

    sequence_id:
      description: Id of the sequence to toggle (entity_id should be the controller).
      example: 1
      example: 1
      required: false
      selector:
        number:
          min: 1
          max: 9999
          mode: box

    zones:
      description: Id(s) of the zone
      example: 1
      required: false
      selector:
        number:
          min: 0
          max: 9999
          mode: box

cancel:
  name: Cancel
  description: Cancel the current run.
  fields:
    entity_id:
      description: Name of the Irrigation Unlimited entity.
      example: "binary_sensor.irrigation_unlimited_c1_z1"
      required: true
      selector:
        entity:
          integration: irrigation_unlimited
          domain: binary_sensor

adjust_time:
  name: Adjust time
  description: Adjust the run times.
  fields:
    entity_id:
      description: Name of the Irrigation Unlimited entity.
      example: "binary_sensor.irrigation_unlimited_c1_z1"
      required: true
      selector:
        entity:
          integration: irrigation_unlimited
          domain: binary_sensor

    sequence_id:
      description: Id of the sequence to adjust (entity_id should be the controller).
      example: 1
      required: false
      selector:
        number:
          min: 1
          max: 9999
          mode: box

    zones:
      description: Id of the zone
      example: 1
      required: false
      selector:
        number:
          min: 0
          max: 9999
          mode: box

    reset:
      description: Revert to original schedule
      example: ""
      required: false

    percentage:
      description: Adjust the run time by a percentage.
      example: "150"
      required: false
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: "%"

    actual:
      description: Set a new run time.
      example: "00:15"
      required: false
      selector:
        duration:

    increase:
      description: Increase the run time.
      example: "00:02"
      required: false
      selector:
        duration:

    decrease:
      description: Decrease the run time.
      example: "00:02"
      required: false
      selector:
        duration:

    minimum:
      description: Minimum run time.
      example: "00:01"
      required: false
      selector:
        duration:

    maximum:
      description: Maximum run time.
      example: "01:00"
      required: false
      selector:
        duration:

manual_run:
  name: Manual run
  description: Turn on immediately for a set period.
  fields:
    entity_id:
      description: Name of the Irrigation Unlimited entity.
      example: "binary_sensor.irrigation_unlimited_c1_z1"
      required: true
      selector:
        entity:
          integration: irrigation_unlimited
          domain: binary_sensor

    time:
      description: The amount of time to run.
      example: "00:10"
      required: false
      selector:
        duration:

    sequence_id:
      description: Id of the sequence to run.
      example: 1
      required: false
      selector:
        number:
          min: 1
          max: 9999
          mode: box

reload:
  name: Reload
  description: Reload the configuration

load_schedule:
  name: Load schedule
  description: Load a schedule.
  fields:
    schedule_id:
      description: Id of the schedule
      example: schedule_1
      required: true
      selector:
        text:
    time:
      description: Time of day
      example: '06:30'
      required: false
      selector:
        time:
    anchor:
      description: Start or finish at the specified time
      example: start
      required: false
      selector:
        select:
          options:
            - start
            - finish
    duration:
      description: The length of time to run
      example: '00:10:00'
      required: false
      selector:
        duration:
    name:
      description: Friendly name of the schedule
      example: Sunrise
      required: false
      selector:
        text:
    weekday:
      description: Days of week to run
      example: mon
      required: false
      selector:
        select:
          multiple: true
          options:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
    month:
      description: Months to run
      example: jan
      required: false
      selector:
        select:
          multiple: true
          options:
            - jan
            - feb
            - mar
            - apr
            - may
            - jun
            - jul
            - aug
            - sep
            - oct
            - nov
            - dec
    day:
      description: Day of month to run
      example: 1
      required: false
      selector:
        object:
    enabled:
      description: Enable/disable this schedule
      example: true
      required: false
      selector:
        boolean:
